---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    resourceVersion: '1127528205'
  name: debug-pipeline
  namespace: stonesoup-int-srvc
  labels:
    app.kubernetes.io/version: '0.1'
spec:
  description: debug
  tasks:
    - name: debug-secret
      taskRef:
        kind: Task
        name: debug-secret
  workspaces:
    - name: release-workspace
