---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: internal-services
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: internal-services
  name: internal-services-leader-election-rolebinding
  namespace: hacbs-internal-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: internal-services-leader-election-role
subjects:
  - kind: ServiceAccount
    name: internal-services-controller-manager
    namespace: hacbs-internal-services
