apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: hacbs-internal-services-resources-errata-template
objects:
  - apiVersion: tekton.dev/v1beta1
    kind: Task
    metadata:
      name: errata-place-holder-task
    spec:
      steps:
        - name: echo
          image: alpine
          script: |
            #!/bin/sh
            echo "Errata Integration"
    
