apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: hacbs-internal-services-resources-iib-template
objects:
  - apiVersion: tekton.dev/v1beta1
    kind: Pipeline
    metadata:
      name: simple-pipeline
      labels:
        app.kubernetes.io/version: "0.1"
      annotations:
        tekton.dev/pipelines.minVersion: "0.12.1"
        tekton.dev/tags: fbc
    spec:
      description: >-
        Tekton pipeline to interact with IIB service for File Based Catalogs
      params:
        - name: iibServiceSecret
          type: string
          description: Secret containing the credentials for IIB service
      workspaces:
        - name: release-workspace
      tasks:
        - name: simple-task
          taskRef:
            name: simple-task
          params:
            - name: IIB_SERVICE_SECRET
              value: $(params.iibServiceSecret)
  - apiVersion: tekton.dev/v1beta1
    kind: Task
    metadata:
      name: simple-task
      labels:
        app.kubernetes.io/version: "0.1"
      annotations:
        tekton.dev/pipelines.minVersion: "0.12.1"
        tekton.dev/tags: release
    spec:
      description: >-
        Submit a build request to add operator bundles to an index image
      params:
        - name: IIB_SERVICE_SECRET
          type: string
          default: "iib-service-account"
          description: Secret with IIB credentials to be used
      steps:
        - name: simple-step
          image: quay.io/hacbs-release/release-utils:latest
          script: |
            #!/usr/bin/env bash
            #
            # adds the json request parameters to a file to be used as input data
            # for curl and preventing shell expansion.
            #
            ls -l /mnt/service-secret/
            PRINCIPAL=$(cat /mnt/service-secret/principal)
            echo "kinit ${PRINCIPAL} -k -t /mnt/service-secret/keytab"
          volumeMounts:
            - name: service-secret
              mountPath: /mnt/service-secret
      volumes:
        - name: service-secret
          secret:
            secretName: $(params.IIB_SERVICE_SECRET)
            defaultMode:
              0400
