apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: hacbs-internal-services-resources-service-account-template
objects:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: pipeline
    secrets:
      - name: iib-service-account
      - name: iib-production-services-config
      - name: errata-service-account
